FROM golang:1.25-alpine AS builder

WORKDIR /app

ARG plugin_name

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o service ./cmd/native-plugins/$plugin_name


FROM scratch

COPY --from=builder /app/service /service

CMD ["/service"]