package types

type HubRecordName string

func (r HubRecordName) ToString() string {
	return string(r)
}

const (
	HubRecordAcceleration  HubRecordName = "acceleration"
	HubRecordBattery       HubRecordName = "battery"
	HubRecordChannel       HubRecordName = "channel"
	HubRecordCO2           HubRecordName = "co2"
	HubRecordConductivity  HubRecordName = "conductivity"
	HubRecordCount         HubRecordName = "count"
	HubRecordCurrent       HubRecordName = "current"
	HubRecordDewPoint      HubRecordName = "dewpoint"
	HubRecordDirection     HubRecordName = "direction"
	HubRecordDistance      HubRecordName = "distance"
	HubRecordDuration      HubRecordName = "duration"
	HubRecordEnergy        HubRecordName = "energy"
	HubRecordGas           HubRecordName = "gas"
	HubRecordGyroscope     HubRecordName = "gyroscope"
	HubRecordHumidity      HubRecordName = "humidity"
	HubRecordIlluminance   HubRecordName = "illuminance"
	HubRecordMass          HubRecordName = "mass"
	HubRecordMoisture      HubRecordName = "moisture"
	HubRecordPM2_5         HubRecordName = "pm2_5"
	HubRecordPM10          HubRecordName = "pm10"
	HubRecordPower         HubRecordName = "power"
	HubRecordPrecipitation HubRecordName = "precipitation"
	HubRecordPressure      HubRecordName = "pressure"
	HubRecordRaw           HubRecordName = "raw"
	HubRecordRotation      HubRecordName = "rotation"
	HubRecordRotational    HubRecordName = "rotational"
	HubRecordSpeed         HubRecordName = "speed"
	HubRecordTemperature   HubRecordName = "temperature"
	HubRecordText          HubRecordName = "text"
	HubRecordTimestamp     HubRecordName = "timestamp"
	HubRecordTVOC          HubRecordName = "tvoc"
	HubRecordVoltage       HubRecordName = "voltage"
	HubRecordVolume        HubRecordName = "volume"
	HubRecordVolumeFlow    HubRecordName = "volume_flow"
	HubRecordUV            HubRecordName = "uv"
	HubRecordWater         HubRecordName = "water"

	// Bool values
	HubRecordBatteryCharging HubRecordName = "battery_charging"
	HubRecordCarbonMonoxide  HubRecordName = "carbon_monoxide"
	HubRecordCold            HubRecordName = "cold"
	HubRecordConnectivity    HubRecordName = "connectivity"
	HubRecordDoor            HubRecordName = "door"
	HubRecordGarageDoor      HubRecordName = "garage_door"
	HubRecordGenericBoolean  HubRecordName = "generic_boolean"
	HubRecordHeat            HubRecordName = "heat"
	HubRecordLight           HubRecordName = "light"
	HubRecordLock            HubRecordName = "lock"
	HubRecordMotion          HubRecordName = "motion"
	HubRecordMoving          HubRecordName = "moving"
	HubRecordOccupancy       HubRecordName = "occupancy"
	HubRecordOpening         HubRecordName = "opening"
	HubRecordPlug            HubRecordName = "plug"
	HubRecordPresence        HubRecordName = "presence"
	HubRecordProblem         HubRecordName = "problem"
	HubRecordRunning         HubRecordName = "running"
	HubRecordSafety          HubRecordName = "safety"
	HubRecordSmoke           HubRecordName = "smoke"
	HubRecordSound           HubRecordName = "sound"
	HubRecordTamper          HubRecordName = "tamper"
	HubRecordVibration       HubRecordName = "vibration"
	HubRecordWindow          HubRecordName = "window"

	// Events
	HubRecordButtonEvent HubRecordName = "button_event"
	HubRecordDimmerEvent HubRecordName = "dimmer_event"
)
